apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/volumes-web-app/upstream/overlays/istio?ref=v1.7.0

patches:
- path: vs.yaml
- path: auth-policy.yaml
