apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jupyter-web-app-jupyter-web-app
spec:
  gateways:
    - istio-system/global-https-external-default-gateway
  hosts:
    - '*'
  http:
    - headers:
        request:
          add:
            x-forwarded-prefix: /jupyter
      match:
        - uri:
            prefix: /jupyter/
      rewrite:
        uri: /
      route:
        - destination:
            host: jupyter-web-app-service.kubeflow.svc.cluster.local
            port:
              number: 80
