# Dockerfile Builder
# ==================
# All the content is in `docker-bits`; this Makefile
# just builds target dockerfiles by combining the dockerbits.


SRC := docker-bits
RESOURCES := resources
OUT := output
TMP := .tmp
TESTS_DIR := ./tests
MAKE_HELPERS := ./make_helpers/
PYTHON_VENV := .venv

# Default labels
DEFAULT_REPO := kubeitglobalsvcauxacrwe.azurecr.io

DEFAULT_PORT := 8888
DEFAULT_NB_PREFIX := /notebook/username/notebookname

.PHONY: clean .output generate-dockerfiles

clean:
	rm -rf $(OUT) $(TMP)

.output:
	mkdir -p $(OUT)/ $(TMP)/

generate-dockerfiles: clean jupyterlab

# create directories for current images
jupyterlab: cpu

	for type in $^; do \
		mkdir -p $(OUT)/$@-$${type}; \
		cp -r resources/common/. $(OUT)/$@-$${type}/; \
		$(CAT) \
			$(TMP)/$${type}.Dockerfile \
			$(SRC)/3_Kubeflow.Dockerfile \
			$(SRC)/4_CLI.Dockerfile \
			$(SRC)/5_DB-Drivers.Dockerfile \
			$(SRC)/6_$(@).Dockerfile \
			$(SRC)/7_remove_vulnerabilities.Dockerfile \
			$(SRC)/8_platform.Dockerfile \
			$(SRC)/∞_CMD.Dockerfile \
		>   $(OUT)/$@-$${type}/Dockerfile; \
	done
