apiVersion: v1
data:
  ADMIN: ''
  ISTIO_INGRESS_GATEWAY_PRINCIPAL: cluster.local/ns/istio-system/sa/global-https-external-default-gateway
  KFP_UI_PRINCIPAL: cluster.local/ns/kubeflow/sa/ml-pipeline-ui
  NOTEBOOK_CONTROLLER_PRINCIPAL: cluster.local/ns/kubeflow/sa/notebook-controller-service-account
  USERID_HEADER: kubeflow-userid
  USERID_PREFIX: ''
  WORKLOAD_IDENTITY: ''
kind: ConfigMap
metadata:
  labels:
    argocd.argoproj.io/instance: kubeflow-profiles
    kustomize.component: profiles
  name: profiles-config
  namespace: kubeflow
