apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=v1.8.1

patches:
  - path: configmap.yaml
  - path: vs.yaml
  # - path: deployment.yaml
